bert_scorer:
  (): bert_score.BERTScorer
  lang: "en"
  rescale_with_baseline: True
  model_type: "bert-base-uncased"

bleu_scorer:
  (): sacrebleu.BLEU
  trg_lang: ""
  effective_order: True


model:
  (): scripts.configs.wrapper.AutoModelForSeq2SeqLMWrapper
  pretrained_model_name_or_path: "t5-base"

tokenizer:
  (): scripts.configs.wrapper.AutoTokenizerWrapper
  pretrained_model_name_or_path: "t5-base"

detectors:
  - (): Todd.MahalanobisScorer
    layers: [-1]
  - (): Todd.CosineProjectionScorer
    layers: [-1]
